[build]
publish = "build/"
command = """
restore_home_cache ".cache" "pip cache" &&
restore_cwd_cache '.venv' 'python virtualenv' &&
pip install -r requirements.txt &&
lektor plugins flush-cache &&
lektor build -f webpack -O ./build
"""
